source 'https://rubygems.org'

gem 'zebra-zpl'
gem 'labelary'
gem 'rainbow'
gem 'activesupport'
gem 'ssdp'
gem 'zeroconf'
gem 'aws-sdk-cognitoidentityprovider'
gem 'aws-cognito-srp'
gem 'nokogiri'
gem 'dotenv'